// players.cjs
module.exports = [
    { name: "Mr. Solis", team: "Team Blue", type: "profesor" },
    { name: "Mr. Aguilera", team: "Team Blue", type: "profesor" },
    { name: "James De Gracia", team: "Team Blue", type: "estudiante", leader: true },
    { name: "Mariangel Castro", team: "Team Blue", type: "estudiante" },
    { name: "Mavielis Castillero", team: "Team Blue", type: "estudiante" },
    { name: "Angui Zhang Qiu", team: "Team Blue", type: "estudiante" },
    { name: "William Chen", team: "Team Blue", type: "estudiante" },
    { name: "Winston Chen", team: "Team Blue", type: "estudiante" },
    { name: "Dylan Rodriguez", team: "Team Blue", type: "estudiante" },
    { name: "Dhruvin Ahir", team: "Team Blue", type: "estudiante" },
    { name: "William Luo Tan", team: "Team Blue", type: "estudiante" },
    { name: "Rocco Lokee", team: "Team Blue", type: "estudiante" },
  
    { name: "Mr. Torres", team: "Team Pink", type: "profesor" },
    { name: "Mr. Pérez", team: "Team Pink", type: "profesor" },
    { name: "Lucas Wu", team: "Team Pink", type: "estudiante", leader: true },
    { name: "Michell Qiu", team: "Team Pink", type: "estudiante" },
    { name: "Isabella Cordero", team: "Team Pink", type: "estudiante" },
    { name: "Anny Deng", team: "Team Pink", type: "estudiante" },
    { name: "Rafael Romero", team: "Team Pink", type: "estudiante" },
    { name: "Ferran Ponton", team: "Team Pink", type: "estudiante" },
    { name: "Brian Chen", team: "Team Pink", type: "estudiante" },
    { name: "Jackson Zhu", team: "Team Pink", type: "estudiante" },
    { name: "Mario Zhong", team: "Team Pink", type: "estudiante" },
    { name: "Kevin Wen", team: "Team Pink", type: "estudiante" },
  
    { name: "Mr. Marmolejo", team: "Team Black", type: "profesor" },
    { name: "Mr. Vergara", team: "Team Black", type: "profesor" },
    { name: "Yoelkis Tuñon", team: "Team Black", type: "estudiante", leader: true },
    { name: "Sarah Aguilar", team: "Team Black", type: "estudiante" },
    { name: "Victoria Pérez", team: "Team Black", type: "estudiante" },
    { name: "Alía Soriano", team: "Team Black", type: "estudiante" },
    { name: "Wilson Chen", team: "Team Black", type: "estudiante" },
    { name: "Joel Pérez", team: "Team Black", type: "estudiante" },
    { name: "Héctor Chen", team: "Team Black", type: "estudiante" },
    { name: "Ellis He", team: "Team Black", type: "estudiante" },
    { name: "José Bertorelli", team: "Team Black", type: "estudiante" },
    { name: "Christopher Wen", team: "Team Black", type: "estudiante" },
  
    { name: "Mr. Hall", team: "Team Red", type: "profesor" },
    { name: "Mrs. Almanza", team: "Team Red", type: "profesor" },
    { name: "Lauren Tapia", team: "Team Red", type: "estudiante", leader: true },
    { name: "Yistka Phipps", team: "Team Red", type: "estudiante" },
    { name: "Samantha Valero", team: "Team Red", type: "estudiante" },
    { name: "Adrián Fernández", team: "Team Red", type: "estudiante" },
    { name: "Jorge Hou", team: "Team Red", type: "estudiante" },
    { name: "Jimmy Chen", team: "Team Red", type: "estudiante" },
    { name: "Edgar Justavino", team: "Team Red", type: "estudiante" },
    { name: "Willy Hou", team: "Team Red", type: "estudiante" },
    { name: "Dylan Sanjur", team: "Team Red", type: "estudiante" },
  ];
  
  